<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitfdfde6c708c7741ddd5d285d6d2db201
{
    public static $files = array (
        '3bc1a7815b04359d6f9e4a13f7f93ffa' => __DIR__ . '/../..' . '/includes/functions/init.php',
    );

    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MTV_Share\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MTV_Share\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes/classes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'MTV_Share\\Setup' => __DIR__ . '/../..' . '/includes/classes/Setup.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitfdfde6c708c7741ddd5d285d6d2db201::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitfdfde6c708c7741ddd5d285d6d2db201::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitfdfde6c708c7741ddd5d285d6d2db201::$classMap;

        }, null, ClassLoader::class);
    }
}
