<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitfdfde6c708c7741ddd5d285d6d2db201
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInitfdfde6c708c7741ddd5d285d6d2db201', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitfdfde6c708c7741ddd5d285d6d2db201', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInitfdfde6c708c7741ddd5d285d6d2db201::getInitializer($loader));

        $loader->setApcuPrefix('6ff807e09fba6616555a');
        $loader->register(true);

        return $loader;
    }
}
