<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '3bc1a7815b04359d6f9e4a13f7f93ffa' => $baseDir . '/includes/functions/init.php',
);
